//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAppFindResource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public int Id { get; set; }
        public string keyName { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<System.DateTime> dateStamp { get; set; }
    }
}
